language: php
php:
#   - '5.6.33'
#   - '7.0.27'
#   - '7.1.13'
#   - '7.2.1'
    - '5.6.32'
    - '7.0.26'
    - '7.1.12'
    - '7.2.0'
os:
    - windows
    - linux
git:
    depth: 1
matrix:
    fast_finish: true
sudo: false
before_install:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2.0" ]]; then git clone -b stable https://github.com/jedisct1/libsodium.git
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2.0" ]]; then cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..
#   - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2.1" ]]; then git clone -b stable https://github.com/jedisct1/libsodium.git
#   - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2.1" ]]; then cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..
install:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2.0" ]]; then pecl install libsodium
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2.0" ]]; then echo "extension=sodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
#   - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2.1" ]]; then pecl install libsodium
#   - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2.1" ]]; then echo "extension=sodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - travis_retry composer install --no-interaction
    - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    - chmod +x coveralls.phar
    - php coveralls.phar --version
before_script:
    - mkdir -p build/logs
    - ls -al
script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
    - travis_retry php coveralls.phar -v
branches:
    only: master
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
